PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT DISTINCT ?item  
WHERE 
{
  ?item wdt:P106 wd:Q937857;  # item hasOccupation associationFootballPlayer
        wdt:P118 wd:Q9448. 
}
